language: groovy

env:
  global:
    - TERM=dumb

script:
  - ./gradlew test --stacktrace

#after_success:
#  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#          gradle uploadArchives --stacktrace -PnexusUsername="${NEXUS_USERNAME}" -PnexusPassword="${NEXUS_PASSWORD}";
#          fi